### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by SamuelVanhaecke** [dedemenezes/legacy_api#2]
Hi, I'm using this api for a project for my programming class but the servers are currently down, was wondering if this will be fixed? Thank you :)

**Comment by dedemenezes** [comment]
Hey @SamuelVanhaecke, my apologies for only seeing it now. I had some i$$ues with Heroku for some days. It is probably when you opened the issue. 

I hope I paid it on time to still support your project.
